import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — Unicorn Idea Filter",
};

const UPDATED = "July 4, 2026";
const CONTACT = "hk@innovateabundance.com";

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="mt-6">
      <h2 className="text-base font-semibold text-zinc-900">{title}</h2>
      <div className="mt-2 space-y-2 text-sm leading-relaxed text-zinc-600">
        {children}
      </div>
    </section>
  );
}

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-2xl">
      <h1 className="text-xl font-semibold tracking-tight text-zinc-900">
        Terms of Service
      </h1>
      <p className="mt-1 text-xs text-zinc-400">Last updated: {UPDATED}</p>

      <p className="mt-4 text-sm leading-relaxed text-zinc-600">
        These terms are a plain-language summary and a starting template — not
        legal advice. Please have them reviewed by a lawyer before relying on
        them.
      </p>

      <Section title="1. Who we are">
        <p>
          This service (the &ldquo;Service&rdquo;) is operated by Innovate
          Abundance LLC (&ldquo;we,&rdquo; &ldquo;us&rdquo;). By using the
          Service you agree to these terms. If you don&apos;t agree, don&apos;t
          use it.
        </p>
      </Section>

      <Section title="2. What the Service is">
        <p>
          The Service is a decision-support tool that scores startup and
          business ideas against structured criteria and generates AI-assisted
          analysis. It is for informational purposes only.
        </p>
        <p>
          Scores, gate results, decisions, and AI output are{" "}
          <strong>not investment, legal, financial, tax, or professional
          advice</strong>, and are not a guarantee of any outcome. You are
          solely responsible for the decisions you make. Do your own diligence.
        </p>
      </Section>

      <Section title="3. Accounts">
        <p>
          You can use parts of the Service anonymously. Some features require an
          account. Keep your login secure and give accurate information;
          you&apos;re responsible for activity under your account.
        </p>
      </Section>

      <Section title="4. Acceptable use">
        <p>You agree not to:</p>
        <ul className="ml-4 list-disc space-y-1">
          <li>use the Service for anything illegal or harmful;</li>
          <li>
            submit content you don&apos;t have the right to share, or another
            party&apos;s confidential information;
          </li>
          <li>
            scrape, resell, reverse-engineer, or abuse the Service, or try to
            evade usage limits or bypass paid features;
          </li>
          <li>
            overload the Service or use it in a way that harms others&apos; use
            of it.
          </li>
        </ul>
      </Section>

      <Section title="5. Your content">
        <p>
          You keep ownership of the ideas and content you enter. You grant us a
          limited license to store, process, and display that content in order
          to operate the Service — including sending it to our AI providers for
          analysis (see the{" "}
          <Link href="/privacy" className="text-teal-700 underline">
            Privacy Policy
          </Link>
          ).
        </p>
        <p>
          Once an idea has been scored it may appear in the public database with
          its scores, an AI summary, an anonymised founder profile, and any
          handle you choose. Your full founder background and identifying
          details are never shown publicly. Paid accounts can keep ideas
          private.
        </p>
      </Section>

      <Section title="6. AI output">
        <p>
          AI analysis is generated by third-party models and may be inaccurate,
          incomplete, or out of date, including any figures produced with web
          search. Treat it as a prompt for your own thinking, and verify
          anything important independently.
        </p>
      </Section>

      <Section title="7. Subscriptions & payments">
        <p>
          Paid subscriptions are billed through Stripe on a recurring basis
          (currently $19/month) until you cancel. You can cancel anytime from
          Settings; access continues to the end of the current billing period.
          Except where required by law, payments are non-refundable. We may
          change pricing or features with reasonable notice.
        </p>
      </Section>

      <Section title="8. Disclaimers & liability">
        <p>
          The Service is provided &ldquo;as is&rdquo; and &ldquo;as
          available,&rdquo; without warranties of any kind. To the fullest
          extent permitted by law, we are not liable for any indirect,
          incidental, or consequential damages, or for decisions made based on
          the Service, and our total liability is limited to the amount you paid
          us in the 12 months before the claim.
        </p>
      </Section>

      <Section title="9. Termination">
        <p>
          You can stop using the Service anytime. We may suspend or terminate
          access if these terms are breached or to protect the Service. You can
          request deletion of your data as described in the Privacy Policy.
        </p>
      </Section>

      <Section title="10. Governing law">
        <p>
          These terms are governed by the laws of the State of Delaware, USA,
          without regard to conflict-of-laws rules, and any disputes will be
          handled in the state or federal courts located in Delaware.
        </p>
      </Section>

      <Section title="11. Changes & contact">
        <p>
          We may update these terms; material changes will be reflected by the
          date above and, where appropriate, a notice in the app. Questions?
          Email{" "}
          <a href={`mailto:${CONTACT}`} className="text-teal-700 underline">
            {CONTACT}
          </a>
          .
        </p>
      </Section>

      <p className="mt-8 text-xs text-zinc-400">
        See also our{" "}
        <Link href="/privacy" className="text-teal-700 underline">
          Privacy Policy
        </Link>
        .
      </p>
    </div>
  );
}
